### ISSUE TITLE
Typo in DESCRIPTION: `bipartide` vs `bipartite` package

### ISSUE THREAD

**Issue by ezherman** [TheoreticalEcology/ecodata#37]
Hi, I tried to install the packages associated with `EcoData` using the following command:

```
devtools::install_github(repo = "TheoreticalEcology/EcoData",
                         dependencies = T, build_vignettes = T)
```

R returned the following warning:

```
package ‘bipartide’ is not available for this version of R
```

I'm guessing this is due to a typo in the DESCRIPTION file, where `bipartide` needs to be `bipartite`.

**Comment by florianhartig** [comment]
Yes, thanks, I fixed this. No idea why I didn't get a warning when trying the install.
