### ISSUE TITLE
seedBank problems

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/ecodata#39]
Hi Max, siehe meine letzten 2 commits, bei den seedbanks musste ich 2 Änderungen machen damit es mit dem anderen Code läuft, kannst du noch mal schauen? Komisch dass es bei dir lief.

**Comment by MaximilianPi** [comment]
Hi Florian, 
ja, hatte eigentlich einen PR für den as.numeric(SBDensity) und die Umbenennung der Variablen. Aber gut, dann kannst den PR löschen und ich push noch etwas für die Hilfe

**Comment by florianhartig** [comment]
mist, ich hatte extra noch geschaut ob es einen PR gibt ... egal, hab ich jetzt gemergt damit die Hilfe passt, danke!
